### ISSUE TITLE
Dev environments improvements

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_cli#351]
- The dev env process should be able to extend the session to retain the data (database etc), and probably use refresh tokens for that
- If a user logs out intentionally, we need to warn them that this will destroy the dev environment and the virtual cluster

**Comment by zipofar** [comment]
Add a persistent flag for the dev environment. For example, user does not want to lose data in volume when dev environment is stopped.

**Comment by gadkins** [comment]
As discussed, we should:
- Do not delete the ucluster namespace when the skaffold process ends  
- Add a `uffizzi dev stop` command that explicitly destroys the ucluster  
- Add warning to the `stop` command to let the user know that volumes will be destroyed  
- Update `uffizzi dev start` to bind the skaffold configuration with the uffizzi json configuration.  
- When the user runs `uffizzi dev start` it should reconnect to existing cluster instead of creating a new instance, i.e. limit of one dev environment per user.

**Comment by moklidia** [comment]
@gadkins `uffizzi dev stop` is used to stop dev clusters in quite mode, because Ctr+C won't stop it in that case. Maybe we can use `uffizzi dev stop` to stop skaffold and `uffizzi dev delete` to delete the cluster?

**Comment by moklidia** [comment]
@zipofar 
`uffizzi dev stop` - stops skaffold
`uffizzi dev delete` - deletes the dev cluster

**Comment by NealArw** [comment]
**Tested - OK**
